### ISSUE TITLE
level 0 and 1 stars mobs conflict with the mod DifficultyScaler

### ISSUE THREAD

**Issue by xzahalko** [JereKuusela/valheim-spawner_tweaks#3]
Hi, 

sorry to bother you, but i have found conflict with DifficultyScaler by CozyHaim.

CozyHaim stopped to develop the mod and as he said on his discord, he gives his code for free use.
Mr.Sunshine has updated the code to the last update of Valheim and corrected the code to scale also level 0 mobs.
I consulted it with Mr.Sunshine and he did not found any reason in the code of DifficultyScaler.

Problem is that level 0 and 1 stars mobs are not scaled when Spawner Tweaks is installed.
From level 2 star mobs scaling works ok.

I just wanted to ask, if you do see any possible connection for this behavior.

Thanks you for your help

**Comment by xzahalko** [comment]
I tested it for example on Meadows with command: spawn greyling 1 0
Scaling for meadows was set to 100,5 %

**Comment by JereKuusela** [comment]
Spawner Tweaks doesn't affect spawn command.

**Comment by xzahalko** [comment]
Ok, thanks
